name = "LALWaveforms"
uuid = "9206b829-cff4-4912-95d2-eb6a5e4d991b"
version = "0.1.0"
authors = ["pseudofractal"]

[workspace]
projects = ["docs"]

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
Libdl = "1.11.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
